### ISSUE TITLE
pad_dim_to() is not implemented

### ISSUE THREAD

**Issue by aspartate** [lucidrains/CoCa-pytorch#18]
The implementation for `pad_dim_to()` seems to be missing from `coca_pytorch.py`.

https://github.com/lucidrains/CoCa-pytorch/blob/0d3f2521a5126e7cc7e58a2374754502944562c7/coca_pytorch/coca_pytorch.py#L29C16-L29C26

**Comment by lucidrains** [comment]
@aspartate 🤦 thanks!

**Comment by aspartate** [comment]
Wow! Thank you for the fast reply!

**Comment by lucidrains** [comment]
you're welcome amino acid stranger
