### ISSUE TITLE
Extractor in vit_pytorch will detach the tensor.

### ISSUE THREAD

**Issue by techkang** [lucidrains/CoCa-pytorch#6]
Thanks for your code! I think I may find a little bug. The cloned tensor in `Extractor` will be detached (https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/extractor.py#L39). So gradient may not propagate back to image encoder.

**Comment by lucidrains** [comment]
@techkang Hi Kang! Yes you are right, should be fixed in 0.35.8 of vit-pytorch! https://github.com/lucidrains/CoCa-pytorch/commit/d70417d5fbee22001d25fc35a89f54cacde8b36a

**Comment by techkang** [comment]
The bug is fixed. Thank you.
