### ISSUE TITLE
Do you plan to give the code for fine-tuning？

### ISSUE THREAD

**Issue by yang178908** [lucidrains/CoCa-pytorch#7]
Hello,
I want to reproduce the VQA task, so do you have any plans to give code about fine-tuning?
Thank you!

**Comment by yoon28** [comment]
+1, one more person also waiting the code :)

**Comment by yuzexing** [comment]
+1, one more person also waiting the code :)

**Comment by rom1504** [comment]
what about using this https://github.com/mlfoundations/open_clip#fine-tuning-coca ? openclip implementation is based on this repo and has pretrained models + doc on how to fine tune

**Comment by lucidrains** [comment]
@yuzexing  @rom1504 what Romain said
