### ISSUE TITLE
How to train the model using my own dataset?

### ISSUE THREAD

**Issue by keepcodeandsmile** [lucidrains/CoCa-pytorch#9]
Can someone tell me how to train the model using my own dataset? is it like below？But I have many images and texts...
``` python
# train by giving CoCa your text and images with `return_loss = True`
loss = coca(
    text = text,
    images = images,
    return_loss = True  # set this to True to get the full caption + contrastive loss
)
```

**Comment by rom1504** [comment]
You could check openclip training scripts as an example.

You need to train this model for several thousand GPU hours to get a small
model trained.
